python finetune.py \
    --base_model 'meta-llama/Llama-2-7b-chat-hf' \
    --data_path './國中生物大雜燴黑板講解-30-45-60.json' \
    --output_dir './國中生物大雜燴黑板講解-30-45-60_epochs4_batch32_meta_llama_7b' \
    --batch_size 32 \
    --micro_batch_size 16 \
    --num_epochs 4 \
    --learning_rate 1e-4 \
    --cutoff_len 512 \
    --val_set_size 10 \
    --lora_r 8 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --lora_target_modules '[q_proj,v_proj]' \
    --train_on_inputs \
    --group_by_length
